### ISSUE TITLE
First-class support for Alameda.js, AMD loader.

### ISSUE THREAD

**Issue by sholladay** [anodynos/uRequire#63]
As a developer who makes 3rd party SaaS libraries for other people's websites, I am frustrated by the module loader landscape. Require.js is good technology, but it's a beast and bloated. Almond.js is great, but too simple for my needs, as it lacks dynamic loading at runtime.

[Alameda.js](https://github.com/requirejs/alameda "Documentation and code for Alameda.js") support within uRequire would make me very happy. And I feel like it fits in well with the spirit of uRequire, to optimize where possible in a clean way.

**Comment by anodynos** [comment]
Thanks for pointing out @sholladay - I will check it out. Its interesting its written by jrburke, the author of RequireJS. 

As it is, uRequire does not mandate what AMD loader you will actually use on your HTML, as far as the AMD template is concerned. 

The combined template uses `almond`, which as you rightly point out is not supporting dynamic loading. That's cause almond is considered as an *internal* mini-loader of your `combined.js`, not as your site overall loading mechanism. With that said, you don't need to restrict your self to what's internal to a `combined.js`. The idea is that you can use just `<script src=''/>` or use another AMD loader (requirejs or Alameda.js or any other) to load both the `combined.js` or other assets, perhaps statically or dynamically/on demand.

I actually want for a next version of uRequire to get rid of almond completely, cause it has an overhead and replace it with [AMDclean](https://github.com/gfranko/amdclean) which will make it smaller and without any trace of AMD.

Hopes this clears it.

**Comment by anodynos** [comment]
I had a quick look at https://github.com/requirejs/alameda but it seems to be abandoned and also not following the AMD standard, so I guess this is not going to be altered - closing issue

**Comment by sholladay** [comment]
There haven't been any commits recently, that's true. But Alameda is pretty stable. My company uses it in production for a 3rd party SaaS app that needs to come bundled with a loader capable of on-demand module loading. It works really well for that without the bloat of RequireJS.

In what way does it diverge from the AMD standard? Definitely curious about any alternatives.

That said, it sounds like I might be able to use uRequire and Alameda together. I wasn't able to figure that out quickly last year, but I could give it another try.

**Comment by anodynos** [comment]
Well, if your AMD modules look like tis example 
```
require(['a', 'b'], function(a, b) {
  // succes callback. Return a value for the next part in the promise chain.
  return [a, b];
}).then(function(mods) {
  //mods[0] is the 'a' module, mods[1] is the 'b' module in this case.
});
```

uRequire will not not know how to parse it (or generate it), cause its only using the plain AMD "standard". Sorry for this, but I dont think there's a lot need to support these kind of modules...

**Comment by sholladay** [comment]
I have never used Alameda in this way. Looks like they [just implemented that](https://github.com/requirejs/alameda/commit/52af5272cf5e619623b90728906302ee63bb6de9) a few days ago. Interesting. Well, it makes sense that uRequire would have a tough time with that. Thanks for the heads up.

**Comment by anodynos** [comment]
You're welcome. 

So, keep in mind that if the module's source is written in the *standard* AMD way, uRequire will have no problem converting either _to AMD_ or _from AMD_. The loader you use at runtime is not the concern of uRequire and should work perfectly. 

Please do keep me posted of any success or failure that you have and also you can provide a git repo with any issues you might have so I can have a look.

Thanks
