### ISSUE TITLE
Prevent Code Convertion

### ISSUE THREAD

**Issue by syaiful6** [anodynos/uRequire#68]
Thanks for the great project, by the way how i prevent uRequire convert the source code? It's look like do
some convertion like:
````
var dest = (function() {
    return [];
})();
````

to something:
````
var dest = function() {
    return [];
}();
````

I use uRequire with grunt, is there any option for this?

**Comment by anodynos** [comment]
Thanks for your kind words - perhaps you can pass some options to esprima codegen, I am not sure this option is supported though. I will look into it and let you know!

**Comment by syaiful6** [comment]
hi @anodynos, dont worry, well i know the generated code is valid. it's just minor issue. 

I think uRequire doesn't have to any code convertion like this, so i open this issue.

**Comment by anodynos** [comment]
Thanks @syaiful6 - you can set a `codegenOptions` object on a `Module` (via a `ResourceConverter`) to force a specific code generated format. I had a look at [escodegen API](https://github.com/estools/escodegen/wiki/API) though and can't find any relevant option... So ill close this issue :-)
