### ISSUE TITLE
http://urequire.org/ down?

### ISSUE THREAD

**Issue by supersven** [anodynos/uRequire#72]
Hey,

http://urequire.org/ asks for username / password and then (as I don't have any) responds with HTTP 401 "Unauthorized".

I guess that's not how it's supposed to be ... :)

So I just wanted to leave you a quick note.

Best regards,

Sven

**Comment by anodynos** [comment]
Thank you @supersven, I know, its cause I had it hosted it on nodjitsu which terminated its service somewhat suddenly - I need to migrate it which I hope I can do soon :-) 

https://www.nodejitsu.com/documentation/nodejitsu-modulus-transition/

**Comment by anodynos** [comment]
http://urequire.org Is now back online again (courtesy of cloudno.de), updated to the (WIP) 0.7.0beta docs.
